### ISSUE TITLE
Get list of majors from UTD website 

### ISSUE THREAD

**Issue by joshcai** [mcdermott-scholars/mcdermott#17]
Get list of majors from UTD website and change the major field to a drop down with the selected options

http://www.utdallas.edu/academics/majors.html

**Comment by atvaccaro** [comment]
Rough-up of code is done, not yet finished compiling whole list.

**Comment by atvaccaro** [comment]
Closed for now since I manually compiled a list. Will re-write the scraper to auto-generate the list of minors eventually.
