### ISSUE TITLE
Add calendar / events support

### ISSUE THREAD

**Issue by joshcai** [mcdermott-scholars/mcdermott#24]
Allow staff to edit. Should display events relevant to the user's class.

**Comment by joshcai** [comment]
https://support.google.com/calendar/answer/45656

We should have these fields so that we can export the events to a personal Google calendar.

**Comment by atvaccaro** [comment]
Basic functionality is complete. Created new issue #38 to separate functionality from look/feel.

**Comment by atvaccaro** [comment]
Should have closed this awhile ago.
